import Chat from '@/app/components/Chat'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from '@/app/components/Providers'
import Navbar from './navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Habeas Codeus',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <Providers>
        <body className={inter.className}>
        <Navbar/>
          <Chat />
          {children}
        </body>
      </Providers>
    </html>
  )
}